### ISSUE TITLE
Big Title Background reverts to Parallax Effect after the last update

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/hestia#53]
[Here is](https://vertis.d.pr/v/sdSBHa) a video about the issue. Basically, after the last update of Hestia free, the Big Title Section will look like this:

![Markup on 2023-01-06 at 13:24:20](https://user-images.githubusercontent.com/26867648/211003290-8664c957-d3e9-4cd5-a010-8bc90cb6d4e9.png)

 Admin area URL: https://bashfulbait.s2-tastewp.com/wp-admin 
 Username: stefancoti 
 Password: tcz0ReX6DvA 

Theme version: 3.0.26

**Comment by cristian-ungureanu** [comment]
cc. @girishpanchal30

**Comment by girishpanchal30** [comment]
@stefan-cotitosu Fixed this issue with this PR https://github.com/Codeinwp/hestia-pro/pull/2469, please check and let me know if you have any issues.

Add the below filter to your current theme functions.php file for an alternate solution

```
add_filter( 'theme_mod_hestia_slider_type', function() {
	return 'image';
}, 99 );
```

Thanks

**Comment by stefan-cotitosu** [comment]
@girishpanchal30, it works, thanks.

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the issue seems to be fixed, but the customizer default images for Parallax are gone. Before this PR, it was like [this](https://vertis.d.pr/i/hmBmIi). After the update, there are no buttons to select the defaults as before https://vertis.d.pr/i/se8fXz , and if i publish the changes without any image selected, the image background will be visible in frontend https://vertis.d.pr/i/tCfEy1 . 
Also, if i select **Image** as Big title background, there will be no image visible [in customizer](https://vertis.d.pr/i/bxkBo2) even if it works ok in frontend

cc @cristian-ungureanu

**Comment by girishpanchal30** [comment]
@irinelenache Mentioned issue is fixed with the latest commit, please check and do let me know if you have any issues.

**Comment by irinelenache** [comment]
@girishpanchal30 The parallax issue is fixed, but this one 

> Also, if i select Image as Big title background, there will be no image visible [in customizer](https://vertis.d.pr/i/bxkBo2) even if it works ok in frontend

is still happening.
You can check on this instance:
```
 Admin area URL: https://hestia-again.s3-tastewp.com/wp-admin 
 Username: irinel 
 Password: i9sUO66fVOg 
```

**Comment by girishpanchal30** [comment]
@irinelenache Fixed, please check with the latest commit

**Comment by irinelenache** [comment]
@girishpanchal30 On a fresh install, the background image is still not visible in customizer (it works in frontend). I have to manually select it from Media library in order to make it work in customizer too https://vertis.d.pr/v/cfdltZ

**Comment by girishpanchal30** [comment]
@irinelenache I've tested with the latest build zip and it seems working fine for me. You can check here...
```
URL: https://rhetoricalsociety.s1-tastewp.com
Username: kwtgirish
Password: i_U0AUy66_k
```

Ref: https://tinyurl.com/2g9spovh

**Comment by irinelenache** [comment]
@girishpanchal30 I checked again and didn't work with your instance either. I think some caching was involved because it works fine in incognito or other browser, sorry for the misunderstanding 🙏 

I'll move this to **Ready to merge** ✅

**Comment by stefan-cotitosu** [comment]
I am reopening this as there are users who reported on wp.org that the latest version of the theme didn't fix the problem. 

They got the Parallax Background image in version 3.0.26, and by updating to 3.0.27, the issue isn't fixed. I asked them to use the filter provided by Girish, and they confirmed it works and solves the issue in version 3.0.27 by they expect a solution without custom code. I'm talking about the following code:

`
add_filter( 'theme_mod_hestia_slider_type', function() {
	return 'image';
}, 99 );
`

Thread where it was reported: https://wordpress.org/support/topic/homepage-bug-with-hestia-3-0-25/page/2/

Here is a video of how I replicated the issue with the latest version: https://vertis.d.pr/v/I7ZZjw

**Comment by girishpanchal30** [comment]
@stefan-cotitosu

> They got the Parallax Background image in version 3.0.26,

Yes, this issue is appearance in version 3.0.26 because this changes the background type 'image' to 'parallax' in the database.
Additionally, version 3.0.27 fixes the problem and does not affect upcoming releases because the version does not automatically switch from "parallax" to "image" OR "image" to "parallax".

So now we have two ways to fix the problem after theme upgrade to version 3.0.27.

1) Re-select the background type in the customizer panel and re-save.
2) Use the filter to change the background type.

I hope you understood.

Thanks

**Comment by stefan-cotitosu** [comment]
Done, thank you, Girish.
